import Image from "next/image";
import { PhoneShell } from "@/components/device/PhoneShell";
import { RevealItem } from "@/components/ui/Reveal";

/**
 * The real application, photographed.
 *
 * These are actual screenshots of the shipped Android build, not the vector
 * mockups used in the hero and the product tour. Both have a place: the vector
 * screens stay sharp at any size, animate their own charts and cost no
 * JavaScript, which is what the hero needs; these are the evidence, which is
 * what a gallery needs.
 *
 * PROCESSING. Each file was cropped before it entered the repository — 4.8% off
 * the top to remove the OS status bar (clock, carrier, signal, battery) and
 * 2.2% off the bottom for the gesture bar. Neither belongs on a marketing page,
 * and the status bar in particular carries information about the device owner.
 *
 * CAPTIONS. Deliberately absent. Naming a screen wrongly is worse than not
 * naming it, and the file order does not correspond to the app's navigation.
 * The frames speak for themselves in a grid; add per-image captions only when
 * each one has been positively identified.
 */

/** Generated by the crop step. Ordered as supplied, not by navigation. */
const SHOTS = Array.from(
  { length: 16 },
  (_, index) => `/screenshots/shot-${String(index + 1).padStart(2, "0")}.jpg`,
);

export function RealGallery() {
  return (
    <ul className="grid grid-cols-2 gap-5 sm:gap-6 md:grid-cols-3 lg:grid-cols-4">
      {SHOTS.map((src, index) => (
        <RevealItem as="li" key={src} index={index % 4}>
          <PhoneShell
            glow={index % 5 === 0}
            label="A screen from the IGNYT Android app"
          >
            <Image
              src={src}
              alt=""
              fill
              /* Four across at desktop inside a 1440px measure, two on mobile.
                 Without this the browser assumes full viewport width and pulls
                 a file four times larger than the slot. */
              sizes="(min-width: 1024px) 300px, (min-width: 640px) 33vw, 45vw"
              className="object-cover"
              /* The first row is close enough to the fold on this page to be
                 worth fetching eagerly; the rest lazy-load as the grid scrolls. */
              priority={index < 4}
            />
          </PhoneShell>
        </RevealItem>
      ))}
    </ul>
  );
}
